### ISSUE TITLE
limited tags

### ISSUE THREAD

**Issue by hades666evil** [pvdspek/jquery.autoellipsis#2]
Hi,
It work great, thanks for this piece of code, but it seems to work with only on certain tags :

&lt;ul id=&quot;container&quot;&gt;
  &lt;li&gt;
      &lt;span&gt;my too long text.&lt;/span&gt;
  &lt;/li&gt;
&lt;/ul&gt;
&lt;/pre&gt;

If I try others tags (div, p ...) or simpler code like 
&lt;div id=&quot;container&quot;&gt;my too long text&lt;/div&gt;
, it fails

**Comment by pvdspek** [comment]
This issue is covered by issue #4.
